name: Power BI Report Deployment

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Power BI CLI
        run: |
          # Install Power BI CLI using npm
          npm i -g @powerbi-cli/powerbi-cli

      - name: Build Power BI report
        run: |
          # Path to your Power BI report file
          REPORT_FILE= "./First_Report.pbix"
          lsattr ./First_Report.pbix
          sudo chmod +rwx ./First_Report.pbix
          sudo chown ubuntu ./First_Report.pbix
          # Build the Power BI report
          pbi import -f ./First_Report.pbix -t "Datasets/Details.csv" -m "firstReport"
